[book]
authors = ["Bit D13"]
language = "en"
multilingual = false
src = "src"
title = "Bench Documentation: Constant price markets on Algorand"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
site-url = "https://docs.myth.finance/bench"
git-repository-url = "https://github.com/MythFinance/docs.myth.finance"
edit-url-template =  "https://github.com/MythFinance/docs.myth.finance/edit/main/bench/{path}"
mathjax-support = true
