[book]
authors = ["Bit D13"]
language = "en"
multilingual = false
src = "src"
title = "Bench Documentation: Constant price markets on Algorand"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
site-url = "https://myth.finance"
mathjax-support = true
